backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "main_info"
    label: "Main Info"
    files:
      - file: "data/site.yml"
        label: "Site Metadata"
        name: "site"
        fields:
          - { label: "Browser Title", name: "title", widget: "string" }
          - { label: "Full Name", name: "name", widget: "string" }
          - { label: "Profile Photo", name: "profile_photo", widget: "image" }

  - name: "about"
    label: "About"
    files:
      - file: "data/about.yml"
        label: "About Me"
        name: "about"
        fields:
          - { label: "About Text", name: "about_text", widget: "text" }

  - name: "skills"
    label: "Skills"
    folder: "content/skills"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Skill", name: "title", widget: "string" }

  - name: "experience"
    label: "Experience"
    folder: "content/experience"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Position", name: "position", widget: "string" }
      - { label: "Company", name: "company", widget: "string" }
      - { label: "Start Date", name: "start", widget: "date" }
      - { label: "End Date", name: "end", widget: "date", required: false }
      - { label: "Description", name: "description", widget: "text" }

  - name: "education"
    label: "Education"
    folder: "content/education"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Degree", name: "degree", widget: "string" }
      - { label: "Institution", name: "institution", widget: "string" }
      - { label: "Year", name: "year", widget: "string" }

  - name: "contact"
    label: "Contact"
    files:
      - file: "data/contact.yml"
        label: "Contact Info"
        name: "contact"
        fields:
          - { label: "Email", name: "email", widget: "string" }
          - { label: "GitHub", name: "github", widget: "string" }
