backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "data/site.yml"
        label: "Site Settings"
        name: "site_settings"
        fields:
          - { label: "Title", name: "title", widget: "string" }
